{
 "title": "UPS",
 "description": "Dashboard for single APC UPS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Battery Charge",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "apcups_battery_charge_percent" }
   ]
  },
  {
   "title": "Charge Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcups_battery_charge_percent", "legendFormat": "Battery" }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    { "expr": "apcups_time_left_seconds / 60" }
   ]
  },
  {
   "title": "UPS Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "apcups_status == 1", "legendFormat": "{{ status }}" }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcups_line_nominal_volts", "legendFormat": "Nominal" },
    { "expr": "apcups_line_volts", "legendFormat": "Actual" }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcups_load_percent", "legendFormat": "Percent" }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apcups_nominal_power_watts*(apcups_load_percent/100)"
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apcups_nominal_power_watts*(apcups_load_percent/100)"
    }
   ]
  }
 ]
}