{
 "title": "Fluentd dashboard (Prometheus exporter)",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Fluentd Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"fluentd.*\"}) / count(node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Output Buffer Queue Lenght",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length * on(pod) group_left(host_ip) kube_pod_info{pod=~\"fluentd.*\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Output Buffer Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes * on(pod) group_left(host_ip) kube_pod_info{pod=~\"fluentd.*\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Emitted Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_emit_records * on(pod) group_left(host_ip) kube_pod_info{pod=~\"fluentd.*\"}",
     "legendFormat": "{{ host_ip }} - {{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_num_errors * on(pod) group_left(host_ip) kube_pod_info{pod=~\"fluentd.*\"}",
     "legendFormat": "{{host_ip}} - {{plugin_id}}"
    }
   ]
  },
  {
   "title": "Retry Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_retry_count * on(pod) group_left(host_ip) kube_pod_info{pod=~\"fluentd.*\"}",
     "legendFormat": "{{host_ip}} - {{plugin_id}}"
    }
   ]
  }
 ]
}