{
 "title": "Traefik  Realtime Metrics",
 "description": "Visualize Traefik Metrics",
 "tags": [ "custom" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average Response Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_request_duration_seconds_sum) / sum(traefik_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{job=\"traefik-ingress-lb\"})"
    }
   ]
  },
  {
   "title": "404 Error Count last 5 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{code=\"404\",method=\"GET\",exported_service=\"http\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_requests_total{exported_service=\"http\"})",
     "legendFormat": "{{http}}"
    },
    {
     "expr": "sum(traefik_requests_total{exported_service=\"https\"})",
     "legendFormat": "{{https}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_request_duration_seconds_sum) / sum(traefik_requests_total) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_requests_total{exported_service=~\"http|https\",code=\"200\"}[5m])",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_requests_total{exported_service=~\"http|https\",code!=\"200\"}[5m])",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests by Request Code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_requests_total{exported_service!~\"http\"}",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_requests_total{exported_service=~\"http|https\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_requests_total{exported_service=~\"http|https\",code!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{exported_service !~ \"http|https\"}[5m])) by (exported_service) ",
     "legendFormat": "{{ exported_service}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{exported_service =~ \"http|https\"}[5m])) by (exported_service) ",
     "legendFormat": "{{ exported_service}}"
    }
   ]
  }
 ]
}